version: 2

builds:
  - id: dzsa-sync
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    main: ./cmd/dzsasync/
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: dzsa-sync
    flags:
      - -v
      - -trimpath

nfpms:
  - id: dzsa-sync
    package_name: dzsa-sync
    builds:
      - dzsa-sync
    file_name_template: '{{ .PackageName }}-{{ .Arch }}'
    homepage: https://github.com/jsirianni/dzsa-sync
    description: Register DayZ servers with dayzsalauncher.com
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - dst: /etc/dzsa-sync
        type: dir
        file_info:
          owner: dzsa-sync
          group: dzsa-sync
          mode: 0750
      - src: package/config.yaml
        dst: /etc/dzsa-sync/config.yaml
        type: "config"
        file_info:
          owner: dzsa-sync
          group: dzsa-sync
          mode: 0640
      - src: package/dzsa-sync.service
        dst: /usr/lib/systemd/system/dzsa-sync.service
        type: "config"
        file_info:
          owner: root
          group: root
          mode: 0640
    scripts:
      preremove: "./package/scripts/preremove.sh"
      postremove: "./package/scripts/postremove.sh"
      preinstall: "./package/scripts/preinstall.sh"
      postinstall: "./package/scripts/postinstall.sh"

archives:
  - format: binary

dockers:
  - id: amd64
    goos: linux
    goarch: amd64
    ids:
      - dzsa-sync
    image_templates:
      - "ghcr.io/jsirianni/dzsa-sync-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/jsirianni/dzsa-sync-amd64:latest"
    dockerfile: package/Dockerfile
    use: buildx
    build_flag_templates:
      - --label=created={{.Date}}
      - --label=title={{.ProjectName}}
      - --label=revision={{.FullCommit}}
      - --label=version={{.Version}}
      - --platform=linux/amd64
      - --label=org.opencontainers.image.source=https://github.com/jsirianni/dzsa-sync
  - id: arm64
    goos: linux
    goarch: arm64
    ids:
      - dzsa-sync
    image_templates:
      - "ghcr.io/jsirianni/dzsa-sync-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/jsirianni/dzsa-sync-arm64:latest"
    dockerfile: package/Dockerfile
    use: buildx
    build_flag_templates:
      - --label=created={{.Date}}
      - --label=title={{.ProjectName}}
      - --label=revision={{.FullCommit}}
      - --label=version={{.Version}}
      - --platform=linux/arm64
      - --label=org.opencontainers.image.source=https://github.com/jsirianni/dzsa-sync

docker_manifests:
  - name_template: "ghcr.io/jsirianni/dzsa-sync:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/jsirianni/dzsa-sync-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/jsirianni/dzsa-sync-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  - name_template: "ghcr.io/jsirianni/dzsa-sync:latest"
    image_templates:
      - "ghcr.io/jsirianni/dzsa-sync-amd64:latest"
      - "ghcr.io/jsirianni/dzsa-sync-arm64:latest"

release:
  draft: false
  prerelease: false
